name: CI/CD Pipeline to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code from GitHub
        uses: actions/checkout@v3

      - name: Copy App files to AWS EC2 securely
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "ansible/app/*"
          target: "/home/ubuntu/app"
          strip_components: 2
          overwrite: true

      - name: SSH into EC2, Build, and Run Docker Container
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/app
            sudo docker build -t b9is121-webapp .
            sudo docker stop my_web_container || true
            sudo docker rm my_web_container || true
            sudo docker run -d -p 80:80 --name my_web_container b9is121-webapp